Add Total Bunch Attributes to Monitor
BLAST-ImpactX/impactx pull request #584
Opened 2024-04-18 17:27 UTC by ax3l

Add our reduced beam characteristics (moments of the particle bunch) as metadata to openPMD files (the beam monitor element).

X-Ref.:
- #533

## Action Items

- [x] implement
- [ ] test that `reduced_beam_characteristics` is indeed an AllReduce now.
- [ ] test and use the new metadata file over the text file in tests
- [ ] document openPMD attributes
- [ ] document openPMD particle "columns" if read back to a dataframe

2024-04-18 18:13 UTC, n01r approved these changes
Looks good. That's really useful! :)

2024-04-24 18:07 UTC, ax3l commented
Will push one more update on the TODOs we marked in the RBC routines - removing reference particle info from it to avoid duplication and collisions.

2024-05-17 15:04 UTC, ax3l commented
ping @RTSandberg @n01r for review :)

2024-05-17 17:32 UTC, cemitch99 reviewed
Just to clarify regarding the reference particle:  
The reference particle data is still written to "ref_particle_," but is no longer duplicated in "reduced_beam_characteristics_".  Instead, it is duplicated in the openPMD output.  

Is this the intent?  Did I miss anything?

2024-05-17 22:20 UTC, RTSandberg commented on examples/pytorch_surrogate_model/visualize_ml_surrogate_15_stage.py
> +ref_gamma = np.sqrt(1 + impactx_surrogate_ref_particle["ref_beta_gamma"] ** 2)
```suggestion
ref_gamma = impactx_surrogate_ref_particle["gamma"]
```

2024-05-17 22:21 UTC, RTSandberg commented on examples/pytorch_surrogate_model/visualize_ml_surrogate_15_stage.py
> +    * impactx_surrogate_ref_particle["ref_beta_gamma"]
```suggestion
    * impactx_surrogate_ref_particle["beta_gamma"]
```

2024-05-17 23:44 UTC, RTSandberg requested changes
This looks good to me; I added a couple revisions to the 15 stages example and it runs for me

2024-05-20 19:18 UTC, ax3l commented
> The reference particle data is still written to "ref_particle_," but is no longer duplicated in "reduced_beam_characteristics_".

Correct. The issue was that it would otherwise collide in names once we combine it to the openPMD output.
If we want, we can still keep the information in the text file output.

> Instead, it is duplicated in the openPMD output.

It should now only be once in the openPMD output using a consistent name for reference particle and collective beam properties; stored as attributes to the beam in each step (iteration).

2024-05-20 19:19 UTC, ax3l commented on src/particles/elements/diagnostics/openPMD.cpp
> +        for(const auto &kv : m_rbc) {
```suggestion
        for (const auto &kv : m_rbc) {
```

2024-05-21 17:27 UTC, RTSandberg approved these changes
Looks good to me!

2024-05-21 18:18 UTC, cemitch99 reviewed
I think it's important that we keep the reference particle text output.  It is a small cost for I/O, and allows a quick check by the user without any postprocessing.

2024-05-21 19:49 UTC, n01r approved these changes
Looks good to me :)

2024-05-22 19:14 UTC, ax3l commented
> I think it's important that we keep the reference particle text output. It is a small cost for I/O, and allows a quick check by the user without any postprocessing.

Good point. We have currently in `diags/` the
- `ref_particle*`
- `reduced_beam_characteristics*`

In the latter, this would remove `s` and `ref_beta_gamma` now. Shall I add `s` again (or both?). We could also make both one file for simplicity.

2024-05-22 19:29 UTC, cemitch99 commented
I think it's good to remove `ref_beta_gamma` from `reduced_beam_characteristics`, since that information is duplicated in the `ref_particle` text output, and it is a "reference" quantity.  However, it would be good to keep the `s` output in both text files, since this is effectively the independent variable characterizing the lattice location.

2024-05-22 19:36 UTC, ax3l commented
Perfect, ok that is what I added back now :)

2024-05-23 02:22 UTC, merged